# Generate src/data/countsMapData.ts from the qgis2web metro map exports.
# Links (selected count sample, classes 4-5) + simplified zone boundaries per metro.
import json
import math

METROS = {
    'telaviv': r"C:\Users\User\Downloads\metro_maps\tlvm\layers",
    'jerusalem': r"C:\Users\User\Downloads\metro_maps\jlm\qgis2web_2026_05_20-10_45_05_433077\layers",
    'haifa': r"C:\Users\User\Downloads\metro_maps\haifa\qgis2web_2026_05_20-10_44_06_328634\layers",
    'beersheva': r"C:\Users\User\Downloads\metro_maps\bs\layers",
}

OUT = r"G:\golan\work\consultant\dev\utilities\portfolio\src\data\countsMapData.ts"


def load(path):
    txt = open(path, encoding='utf-8').read()
    return json.loads(txt[txt.index('{'):])


def rdp(points, eps):
    """Ramer-Douglas-Peucker in degree space."""
    if len(points) < 3:
        return points
    x1, y1 = points[0]
    x2, y2 = points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy)
    dmax, idx = 0.0, 0
    for i in range(1, len(points) - 1):
        px_, py_ = points[i]
        if norm == 0:
            d = math.hypot(px_ - x1, py_ - y1)
        else:
            d = abs(dy * px_ - dx * py_ + x2 * y1 - y2 * x1) / norm
        if d > dmax:
            dmax, idx = d, i
    if dmax > eps:
        left = rdp(points[:idx + 1], eps)
        right = rdp(points[idx:], eps)
        return left[:-1] + right
    return [points[0], points[-1]]


def rnd(coords):
    return [[round(c[0], 4), round(c[1], 4)] for c in coords]


def dedupe(coords):
    out = [coords[0]]
    for c in coords[1:]:
        if c != out[-1]:
            out.append(c)
    return out


def ts_str(s):
    return json.dumps(s, ensure_ascii=False)


parts = []
parts.append("// AUTO-GENERATED by scripts/gen-counts-map-data.py — do not edit by hand.")
parts.append("// Selected traffic-count links (road classes 4-5) + zone boundaries per metro,")
parts.append("// simplified from the QGIS network-analysis exports.")
parts.append("")
parts.append("export type MetroKey = 'telaviv' | 'jerusalem' | 'haifa' | 'beersheva';")
parts.append("")
parts.append("export interface CountLink {")
parts.append("    /** street name (Hebrew, from the model network) */")
parts.append("    n: string | null;")
parts.append("    /** road number */")
parts.append("    r: string | null;")
parts.append("    /** raw betweenness centrality score */")
parts.append("    c: number;")
parts.append("    /** link length in meters */")
parts.append("    l: number;")
parts.append("    /** polyline paths [ [ [lon,lat], ... ], ... ] */")
parts.append("    p: number[][][];")
parts.append("}")
parts.append("")
parts.append("export interface MetroData {")
parts.append("    links: CountLink[];")
parts.append("    /** zone boundary rings (simplified) */")
parts.append("    zones: number[][][];")
parts.append("}")
parts.append("")

metro_entries = []
for key, d in METROS.items():
    links_json = load(d + r"\AnalysisResults_2.js")
    zones_json = load(d + r"\Zones_1.js")

    link_items = []
    for f in links_json['features']:
        pr = f['properties']
        cent = pr.get('centrality') or 0.0
        name = pr.get('NAME') or None
        road = pr.get('ROADNUMBER') or None
        length = round(pr.get('_length_m') or 0.0)
        geom = f['geometry']
        lines = geom['coordinates'] if geom['type'] == 'MultiLineString' else [geom['coordinates']]
        paths = []
        for line in lines:
            simplified = rnd(dedupe(rdp([list(c) for c in line], 0.0002)))
            if len(simplified) >= 2:
                paths.append(simplified)
        if not paths:
            continue
        link_items.append({'n': name, 'r': road, 'c': cent, 'l': length, 'p': paths})

    # sort by centrality so high-centrality links render last (on top)
    link_items.sort(key=lambda x: x['c'])

    zone_rings = []
    for f in zones_json['features']:
        geom = f['geometry']
        polys = geom['coordinates'] if geom['type'] == 'MultiPolygon' else [geom['coordinates']]
        for poly in polys:
            ring = rnd(dedupe(rdp([list(c) for c in poly[0]], 0.0012)))
            if len(ring) >= 4:
                zone_rings.append(ring)

    links_ts = ',\n'.join(
        '        {n:%s,r:%s,c:%s,l:%s,p:%s}' % (
            ts_str(it['n']) if it['n'] else 'null',
            ts_str(it['r']) if it['r'] else 'null',
            json.dumps(it['c']),
            it['l'],
            json.dumps(it['p'], separators=(',', ':')),
        ) for it in link_items
    )
    zones_ts = ',\n'.join('        ' + json.dumps(r, separators=(',', ':')) for r in zone_rings)
    metro_entries.append(
        "    %s: {\n        links: [\n%s\n        ],\n        zones: [\n%s\n        ],\n    }" % (key, links_ts, zones_ts)
    )
    print(key, 'links:', len(link_items), 'zone rings:', len(zone_rings))

parts.append("export const COUNTS_METROS: Record<MetroKey, MetroData> = {")
parts.append(',\n'.join(metro_entries))
parts.append("};")
parts.append("")

out_txt = '\n'.join(parts)
open(OUT, 'w', encoding='utf-8').write(out_txt)
print('wrote', OUT, len(out_txt) // 1024, 'KB')
